[package]
name = "event-hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.183"
aes-gcm = "0.10.2"
base64 = "0.21.2"
serde_json = "1.0.104"
generic-array = "0.14.7"
